### ISSUE TITLE
Derivative profiles

### ISSUE THREAD

**Issue by anders-kiaer** [Statoil/stea#13]
Tested the python package `stea` on a real life project. In the STEA-project delivered from the economist, of the 18 profiles in the project, only three of them are actual input (`FOPT`, `FGPT`, cost). The rest of the profiles are derivatives using simple spreadsheet formulas like `=I4*H6`.

STEA server does not recalculate the derivate profiles when the input profiles are modified in batch mode (it uses the values previously stored/calculated using the desktop version). This could be a source of user mistake, when running `stea` in batch mode. 

**Three possible solutions/mitigating actions (other options probably also exist):**

1) STEA software/server updates the derivative profiles when changing input profiles (probably *the* solution, if this is feasible).

2) `stea` python package offers a user friendly way of inputting derivative profiles. The batch mode end-user then uses this framework to replicate the derivative profiles entered by the economist in the STEA project.
   - **Advantage:** Robust wrt. software/running time errors.
   - **Disadvantage:** Duplication of work between batch user and economist. Risk getting out-of sync.

3) `stea` python package reads the project's `xml` file and does the spreadsheet like calculations automatically. A workflow could be:
   1) Parse [STEA xml project file](https://docs.python.org/3/library/xml.html) (example `xml` STEA-project snippet below).
   2) Discover the derivative profiles, put the equations in a DAG and run topological sort using [networkx](https://github.com/networkx/networkx) (to ensure the spreadsheet like calculations are done in a correct order).
   3) Use [sympy](https://github.com/sympy/sympy) to evaluate the expressions and get the derivative profiles. `sympy` can also be used to find the variables that goes into an expression, facilitating the setup of the DAG above.

   - **Advantage:** Less risk of getting out of sync + avoid duplicating economist setup.
   - **Disadvantage:** Need to develop/maintain more code compared with option 2) + dependency on `stea xml` structure.

```xml
<Profile xsi:type="QuantityProfile">
      <UniqueID>55421815</UniqueID>
      <Name>My derivative profile</Name>
      ...
      <ProjectSheetSpecificSettings>
        <Formulas>
          <item>
            <key>
              <int>2017</int>
            </key>
            <value>
              <string>=G4*G7</string>
            </value>
          </item>
          ...
          <item>
            <key>
              <int>2032</int>
            </key>
            <value>
              <string>=V4*V7</string>
            </value>
          </item>
        </Formulas>
        <GuiRowNumber>5</GuiRowNumber>
      </ProjectSheetSpecificSettings>
      ...
</Profile>
```

**Comment by joakim-hove** [comment]
Alternative 1

**Comment by lahus2** [comment]
Alternative 1 would be the easiest, but I think that COMSOL mentioned it was a lot more complex. I think it was go on the list of possible improvements if there is a continuation of the project with them in future.

As another possible solution:

All the profiles I saw were multipliers (e.g. FOPT*0.01). I think we could get an awfully long way to solving this by just adding a multiplier option on a profile. I had planned on look at that this week.

**Comment by anders-kiaer** [comment]
In the real test case you also had examples of basically `(another array)*FGPT`, multiplied element by element. In the STEA template project, this is apparently implemented as three profiles (the `FOPT` input profile, a static `another array` with numerical values, and a derivative profile with spreadsheet equations e.g. `=K3*L3`).

If the "input problem" is solved using alternative 2, there is a risk of getting "out-of-sync" (since the end-batch-user + economist have to update the derivative profiles in two places).

**Comment by anders-kiaer** [comment]
Alternative 1 implemented. Closing.
